<?php

interface ReturnCodes
{
	const ERROR_MESSAGE = "Something went wrong";

	const LOGIN_EMAIL_CORRECT = 100;
	const LOGIN_EMAIL_WRONG = 101;

	const LOGIN_PASSWORD_CORRECT = 110;
	const LOGIN_PASSWORD_WRONG = 111;

	const SIGNIN_ACCOUNT_SUCCESS = 200;
	const SIGNIN_ACCOUNT_ALREADY_EXISTS = 201;

	const TRANSACTION_TABLE_FILLED = 300;
	const TRANSACTION_TABLE_EMPTY = 301;

	const TRANSACTION_RECIPIENT_SUCCESS = 400;
	const TRANSACTION_RECIPIENT_SELF = 401;
	const TRANSACTION_RECIPIENT_NOT_FOUND = 402;
	
	const TRANSACTION_AMOUNT_SUCCESS = 500;
	const TRANSACTION_AMOUNT_LIMIT_OVER = 501;
	const TRANSACTION_AMOUNT_LIMIT_EQUAL = 502;

	const INSUFFICIENT_BALANCE = -1;
	const EMPTY_BALANCE_AFTER_TRANSACTION = 0;
	const SUFFICIENT_BALANCE = 1;
}

?>